name: ItemControl
main: no.runsafe.ItemControl.ItemControl
version: 1.0.@BUILD@
author: Kruithne
authors: [mortenn]
depend: [RunsafeWorldGuardBridge]
description: Item control for Minecraft (CraftBukkit)
commands:
  traders:
    description: Trader related commands